"""Utilities for constructing an attribute graph using pointwise mutual information.

The :class:`PMIAttributeGraph` class builds an undirected NetworkX graph where
nodes correspond to attribute tokens derived from dataset metadata. Edges are
weighted by pointwise mutual information (PMI) computed from token
co-occurrences. Consumers can reuse the PMI scores to reason about relational
strength between attributes or export the resulting adjacency matrix for
downstream models.
"""
from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from math import log
from pathlib import Path
from typing import Iterable, Mapping, Sequence

import networkx as nx
import pandas as pd

__all__ = ["PMIAttributeGraph", "load_metadata"]


@dataclass
class PMIStats:
    """Container storing intermediate PMI statistics."""

    token_counts: Counter[str]
    co_occurrence: Mapping[tuple[str, str], int]
    total_samples: int


def load_metadata(path: str | Path) -> pd.DataFrame:
    """Load the dataset metadata file generated by ``generate_shapes_dataset``.

    Parameters
    ----------
    path:
        Path to a JSON metadata file.

    Returns
    -------
    pandas.DataFrame
        Table containing one row per generated sample with columns for each
        attribute alongside the image filename.
    """

    path = Path(path)
    if path.suffix != ".json":
        raise ValueError("Expected a JSON metadata file produced by generate_shapes_dataset")
    return pd.read_json(path)


class PMIAttributeGraph:
    """Construct an attribute graph using pointwise mutual information.

    Examples
    --------
    >>> from dierpian.data.generate_shapes_dataset import generate_shapes_dataset
    >>> from dierpian.graphs.pmi_attribute_graph import PMIAttributeGraph
    >>> metadata = generate_shapes_dataset("data")
    >>> graph_builder = PMIAttributeGraph()
    >>> graph_builder.fit(metadata)
    >>> graph_builder.graph.number_of_nodes() > 0
    True

    Notes
    -----
    PMI is computed between unordered token pairs. Each metadata row is
    converted into tokens of the form ``"{column}={value}"``. Probabilities are
    estimated using maximum likelihood with Laplace smoothing, helping stabilise
    PMI scores for rarely observed combinations.
    """

    def __init__(self, min_pmi: float = 0.0, smoothing: float = 1.0) -> None:
        self.min_pmi = min_pmi
        self.smoothing = smoothing
        self.graph: nx.Graph = nx.Graph()
        self._stats: PMIStats | None = None

    @staticmethod
    def _iter_tokens(metadata: Iterable[Mapping[str, object]]) -> Iterable[list[str]]:
        for row in metadata:
            tokens = []
            for key, value in row.items():
                if key == "filename":
                    continue
                tokens.append(f"{key}={value}")
            yield tokens

    def _accumulate_stats(self, metadata: Iterable[Mapping[str, object]]) -> PMIStats:
        token_counts: Counter[str] = Counter()
        co_occurrence: Counter[tuple[str, str]] = Counter()
        total_samples = 0

        for tokens in self._iter_tokens(metadata):
            unique_tokens = sorted(set(tokens))
            total_samples += 1
            token_counts.update(unique_tokens)
            for i, token_i in enumerate(unique_tokens):
                for token_j in unique_tokens[i + 1 :]:
                    co_occurrence[(token_i, token_j)] += 1

        return PMIStats(token_counts, co_occurrence, total_samples)

    def fit(self, metadata: Sequence[Mapping[str, object]]) -> "PMIAttributeGraph":
        """Compute PMI statistics and populate the graph.

        Parameters
        ----------
        metadata:
            Sequence of dictionaries or dataclass instances describing dataset
            rows. The object should be convertible to a mapping via ``vars`` or
            ``asdict``. Each element must at least expose ``shape`` and
            ``color`` keys but arbitrary additional columns are supported.

        Returns
        -------
        PMIAttributeGraph
            Self to enable method chaining.
        """

        normalised_metadata: list[Mapping[str, object]] = []
        for row in metadata:
            if isinstance(row, Mapping):
                normalised_metadata.append(row)
            else:
                normalised_metadata.append(vars(row))

        stats = self._accumulate_stats(normalised_metadata)
        self._stats = stats
        self.graph.clear()

        # Add nodes
        for token, count in stats.token_counts.items():
            self.graph.add_node(token, count=count)

        total = stats.total_samples
        vocab = set(stats.token_counts.keys())
        for token in vocab:
            self.graph.nodes[token]["p"] = (stats.token_counts[token] + self.smoothing) / (
                total + self.smoothing * len(vocab)
            )

        # Compute PMI edges
        for (token_i, token_j), joint_count in stats.co_occurrence.items():
            p_i = self.graph.nodes[token_i]["p"]
            p_j = self.graph.nodes[token_j]["p"]
            joint = (joint_count + self.smoothing) / (total + self.smoothing * len(vocab))
            pmi = log(joint / (p_i * p_j))
            if pmi >= self.min_pmi:
                self.graph.add_edge(token_i, token_j, weight=pmi, joint_count=joint_count)

        return self

    def adjacency_matrix(self) -> pd.DataFrame:
        """Return the symmetric adjacency matrix indexed by tokens."""

        if not self.graph:
            raise ValueError("The graph is empty; call `fit` first")
        nodes = sorted(self.graph.nodes())
        matrix = pd.DataFrame(0.0, index=nodes, columns=nodes)
        for u, v, data in self.graph.edges(data=True):
            matrix.loc[u, v] = matrix.loc[v, u] = data.get("weight", 0.0)
        return matrix

    def neighbours(self, token: str, top_k: int | None = None) -> list[tuple[str, float]]:
        """Return nearest neighbours of ``token`` sorted by PMI weight."""

        if token not in self.graph:
            raise KeyError(f"Token {token!r} not found in graph")
        neighbours = [
            (nbr, data.get("weight", 0.0))
            for nbr, data in sorted(
                self.graph[token].items(), key=lambda item: item[1].get("weight", 0.0), reverse=True
            )
        ]
        if top_k is not None:
            return neighbours[:top_k]
        return neighbours

    def to_edge_list(self) -> list[tuple[str, str, float]]:
        """Export the edge list as ``(token_i, token_j, weight)`` tuples."""

        return [(u, v, data.get("weight", 0.0)) for u, v, data in self.graph.edges(data=True)]

    @property
    def stats(self) -> PMIStats:
        """Return the cached :class:`PMIStats` from the last ``fit`` call."""

        if self._stats is None:
            raise ValueError("PMI statistics are not available; call `fit` first")
        return self._stats
